Cluster Name : Groups+Command Name : AddGroup+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t *+Argument Name : groupName
Cluster Name : Groups+Command Name : AddGroupIfIdentifying+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t *+Argument Name : groupName
Cluster Name : Groups+Command Name : GetGroupMembership+Type Name : uint8_t+Argument Name : groupCount,Type Name : uint16_t+Argument Name : groupList
Cluster Name : Groups+Command Name : RemoveAllGroups
Cluster Name : Groups+Command Name : RemoveGroup+Type Name : uint16_t+Argument Name : groupId
Cluster Name : Groups+Command Name : ViewGroup+Type Name : uint16_t+Argument Name : groupId
Cluster Name : Groups+Command Name : AddGroupResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : groupId
Cluster Name : Groups+Command Name : GetGroupMembershipResponse+Type Name : uint8_t+Argument Name : capacity,Type Name : uint8_t+Argument Name : groupCount,Type Name : uint16_t+Argument Name : groupList
Cluster Name : Groups+Command Name : RemoveGroupResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : groupId
Cluster Name : Groups+Command Name : ViewGroupResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t *+Argument Name : groupName
Cluster Name : Identify+Command Name : Identify+Type Name : uint16_t+Argument Name : identifyTime
Cluster Name : Identify+Command Name : IdentifyQuery
Cluster Name : Identify+Command Name : TriggerEffect+Type Name : EmberAfIdentifyEffectIdentifier+Argument Name : effectId,Type Name : EmberAfIdentifyEffectVariant+Argument Name : effectVariant
Cluster Name : Identify+Command Name : IdentifyQueryResponse+Type Name : uint16_t+Argument Name : timeout
Cluster Name : LevelControl+Command Name : Move+Type Name : EmberAfMoveMode+Argument Name : moveMode,Type Name : uint8_t+Argument Name : rate,Type Name : uint8_t+Argument Name : optionMask,Type Name : uint8_t+Argument Name : optionOverride
Cluster Name : LevelControl+Command Name : MoveToLevel+Type Name : uint8_t+Argument Name : level,Type Name : uint16_t+Argument Name : transitionTime,Type Name : uint8_t+Argument Name : optionMask,Type Name : uint8_t+Argument Name : optionOverride
Cluster Name : LevelControl+Command Name : MoveToLevelWithOnOff+Type Name : uint8_t+Argument Name : level,Type Name : uint16_t+Argument Name : transitionTime
Cluster Name : LevelControl+Command Name : MoveWithOnOff+Type Name : EmberAfMoveMode+Argument Name : moveMode,Type Name : uint8_t+Argument Name : rate
Cluster Name : LevelControl+Command Name : Step+Type Name : EmberAfStepMode+Argument Name : stepMode,Type Name : uint8_t+Argument Name : stepSize,Type Name : uint16_t+Argument Name : transitionTime,Type Name : uint8_t+Argument Name : optionMask,Type Name : uint8_t+Argument Name : optionOverride
Cluster Name : LevelControl+Command Name : StepWithOnOff+Type Name : EmberAfStepMode+Argument Name : stepMode,Type Name : uint8_t+Argument Name : stepSize,Type Name : uint16_t+Argument Name : transitionTime
Cluster Name : LevelControl+Command Name : Stop+Type Name : uint8_t+Argument Name : optionMask,Type Name : uint8_t+Argument Name : optionOverride
Cluster Name : LevelControl+Command Name : StopWithOnOff
Cluster Name : OnOff+Command Name : Off
Cluster Name : OnOff+Command Name : OffWithEffect+Type Name : EmberAfOnOffEffectIdentifier+Argument Name : effectId,Type Name : uint8_t+Argument Name : effectVariant
Cluster Name : OnOff+Command Name : On
Cluster Name : OnOff+Command Name : OnWithRecallGlobalScene
Cluster Name : OnOff+Command Name : OnWithTimedOff+Type Name : uint8_t+Argument Name : onOffControl,Type Name : uint16_t+Argument Name : onTime,Type Name : uint16_t+Argument Name : offWaitTime
Cluster Name : OnOff+Command Name : Toggle
Cluster Name : OverTheAirBootloading+Command Name : ImageBlockRequest+Type Name : uint8_t+Argument Name : fieldControl,Type Name : uint16_t+Argument Name : manufacturerId,Type Name : uint16_t+Argument Name : imageType,Type Name : uint32_t+Argument Name : fileVersion,Type Name : uint32_t+Argument Name : fileOffset,Type Name : uint8_t+Argument Name : maxDataSize,Type Name : uint8_t *+Argument Name : requestNodeAddress
Cluster Name : OverTheAirBootloading+Command Name : QueryNextImageRequest+Type Name : uint8_t+Argument Name : fieldControl,Type Name : uint16_t+Argument Name : manufacturerId,Type Name : uint16_t+Argument Name : imageType,Type Name : uint32_t+Argument Name : currentFileVersion,Type Name : uint16_t+Argument Name : hardwareVersion
Cluster Name : OverTheAirBootloading+Command Name : UpgradeEndRequest+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : manufacturerId,Type Name : uint16_t+Argument Name : imageType,Type Name : uint32_t+Argument Name : fileVersion
Cluster Name : OverTheAirBootloading+Command Name : ImageBlockResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : manufacturerId,Type Name : uint16_t+Argument Name : imageType,Type Name : uint32_t+Argument Name : fileVersion,Type Name : uint32_t+Argument Name : fileOffset,Type Name : uint8_t+Argument Name : dataSize,Type Name : uint8_t+Argument Name : imageData
Cluster Name : OverTheAirBootloading+Command Name : ImageNotify+Type Name : uint8_t+Argument Name : payloadType,Type Name : uint8_t+Argument Name : queryJitter,Type Name : uint16_t+Argument Name : manufacturerId,Type Name : uint16_t+Argument Name : imageType,Type Name : uint32_t+Argument Name : newFileVersion
Cluster Name : OverTheAirBootloading+Command Name : QueryNextImageResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : manufacturerId,Type Name : uint16_t+Argument Name : imageType,Type Name : uint32_t+Argument Name : fileVersion,Type Name : uint32_t+Argument Name : imageSize
Cluster Name : OverTheAirBootloading+Command Name : UpgradeEndResponse+Type Name : uint16_t+Argument Name : manufacturerId,Type Name : uint16_t+Argument Name : imageType,Type Name : uint32_t+Argument Name : fileVersion,Type Name : uint32_t+Argument Name : currentTime,Type Name : uint32_t+Argument Name : upgradeTime
Cluster Name : Scenes+Command Name : AddScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId,Type Name : uint16_t+Argument Name : transitionTime,Type Name : uint8_t *+Argument Name : sceneName,Type Name : EmberAfSceneExtensionFieldSet+Argument Name : extensionFieldSets
Cluster Name : Scenes+Command Name : CopyScene+Type Name : uint8_t+Argument Name : mode,Type Name : uint16_t+Argument Name : groupIdFrom,Type Name : uint8_t+Argument Name : sceneIdFrom,Type Name : uint16_t+Argument Name : groupIdTo,Type Name : uint8_t+Argument Name : sceneIdTo
Cluster Name : Scenes+Command Name : EnhancedAddScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId,Type Name : uint16_t+Argument Name : transitionTime,Type Name : uint8_t *+Argument Name : sceneName,Type Name : EmberAfSceneExtensionFieldSet+Argument Name : extensionFieldSets
Cluster Name : Scenes+Command Name : EnhancedViewScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : Scenes+Command Name : GetSceneMembership+Type Name : uint16_t+Argument Name : groupId
Cluster Name : Scenes+Command Name : RecallScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId,Type Name : uint16_t+Argument Name : transitionTime
Cluster Name : Scenes+Command Name : RemoveAllScenes+Type Name : uint16_t+Argument Name : groupId
Cluster Name : Scenes+Command Name : RemoveScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : Scenes+Command Name : StoreScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : Scenes+Command Name : ViewScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : Scenes+Command Name : AddSceneResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : Scenes+Command Name : GetSceneMembershipResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint8_t+Argument Name : capacity,Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneCount,Type Name : uint8_t+Argument Name : sceneList
Cluster Name : Scenes+Command Name : RemoveAllScenesResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : groupId
Cluster Name : Scenes+Command Name : RemoveSceneResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : Scenes+Command Name : StoreSceneResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : Scenes+Command Name : ViewSceneResponse+Type Name : EmberAfStatus+Argument Name : status,Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId,Type Name : uint16_t+Argument Name : transitionTime,Type Name : uint8_t *+Argument Name : sceneName,Type Name : EmberAfSceneExtensionFieldSet+Argument Name : extensionFieldSets
Cluster Name : ZLLCommissioning+Command Name : DeviceInformationRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t+Argument Name : startIndex
Cluster Name : ZLLCommissioning+Command Name : GetEndpointListRequest+Type Name : uint8_t+Argument Name : startIndex
Cluster Name : ZLLCommissioning+Command Name : GetGroupIdentifiersRequest+Type Name : uint8_t+Argument Name : startIndex
Cluster Name : ZLLCommissioning+Command Name : IdentifyRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint16_t+Argument Name : identifyDuration
Cluster Name : ZLLCommissioning+Command Name : NetworkJoinEndDeviceRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t *+Argument Name : extendedPanId,Type Name : EmberAfKeyIndex+Argument Name : keyIndex,Type Name : /* TYPE WARNING: security_key defaults to */ uint8_t * +Argument Name : encryptedNetworkKey,Type Name : uint8_t+Argument Name : networkUpdateId,Type Name : uint8_t+Argument Name : logicalChannel,Type Name : uint16_t+Argument Name : panId,Type Name : uint16_t+Argument Name : networkAddress,Type Name : uint16_t+Argument Name : groupIdentifiersBegin,Type Name : uint16_t+Argument Name : groupIdentifiersEnd,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeBegin,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeEnd,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeBegin,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeEnd
Cluster Name : ZLLCommissioning+Command Name : NetworkJoinRouterRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t *+Argument Name : extendedPanId,Type Name : EmberAfKeyIndex+Argument Name : keyIndex,Type Name : /* TYPE WARNING: security_key defaults to */ uint8_t * +Argument Name : encryptedNetworkKey,Type Name : uint8_t+Argument Name : networkUpdateId,Type Name : uint8_t+Argument Name : logicalChannel,Type Name : uint16_t+Argument Name : panId,Type Name : uint16_t+Argument Name : networkAddress,Type Name : uint16_t+Argument Name : groupIdentifiersBegin,Type Name : uint16_t+Argument Name : groupIdentifiersEnd,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeBegin,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeEnd,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeBegin,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeEnd
Cluster Name : ZLLCommissioning+Command Name : NetworkStartRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t *+Argument Name : extendedPanId,Type Name : EmberAfKeyIndex+Argument Name : keyIndex,Type Name : /* TYPE WARNING: security_key defaults to */ uint8_t * +Argument Name : encryptedNetworkKey,Type Name : uint8_t+Argument Name : logicalChannel,Type Name : uint16_t+Argument Name : panId,Type Name : uint16_t+Argument Name : networkAddress,Type Name : uint16_t+Argument Name : groupIdentifiersBegin,Type Name : uint16_t+Argument Name : groupIdentifiersEnd,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeBegin,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeEnd,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeBegin,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeEnd,Type Name : uint8_t *+Argument Name : initiatorIeeeAddress,Type Name : uint16_t+Argument Name : initiatorNetworkAddress
Cluster Name : ZLLCommissioning+Command Name : NetworkUpdateRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t *+Argument Name : extendedPanId,Type Name : uint8_t+Argument Name : networkUpdateId,Type Name : uint8_t+Argument Name : logicalChannel,Type Name : uint16_t+Argument Name : panId,Type Name : uint16_t+Argument Name : networkAddress
Cluster Name : ZLLCommissioning+Command Name : ResetToFactoryNewRequest+Type Name : uint32_t+Argument Name : transaction
Cluster Name : ZLLCommissioning+Command Name : ScanRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t+Argument Name : zigbeeInformation,Type Name : uint8_t+Argument Name : zllInformation
Cluster Name : ZLLCommissioning+Command Name : DeviceInformationResponse+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t+Argument Name : numberOfSubDevices,Type Name : uint8_t+Argument Name : startIndex,Type Name : uint8_t+Argument Name : deviceInformationRecordCount,Type Name : EmberAfDeviceInformationRecord+Argument Name : deviceInformationRecordList
Cluster Name : ZLLCommissioning+Command Name : EndpointInformation+Type Name : uint8_t *+Argument Name : ieeeAddress,Type Name : uint16_t+Argument Name : networkAddress,Type Name : uint8_t+Argument Name : endpointId,Type Name : uint16_t+Argument Name : profileId,Type Name : uint16_t+Argument Name : deviceId,Type Name : uint8_t+Argument Name : version
Cluster Name : ZLLCommissioning+Command Name : GetEndpointListResponse+Type Name : uint8_t+Argument Name : total,Type Name : uint8_t+Argument Name : startIndex,Type Name : uint8_t+Argument Name : count,Type Name : EmberAfEndpointInformationRecord+Argument Name : endpointInformationRecordList
Cluster Name : ZLLCommissioning+Command Name : GetGroupIdentifiersResponse+Type Name : uint8_t+Argument Name : total,Type Name : uint8_t+Argument Name : startIndex,Type Name : uint8_t+Argument Name : count,Type Name : EmberAfGroupInformationRecord+Argument Name : groupInformationRecordList
Cluster Name : ZLLCommissioning+Command Name : NetworkJoinEndDeviceResponse+Type Name : uint32_t+Argument Name : transaction,Type Name : EmberAfZllStatus+Argument Name : status
Cluster Name : ZLLCommissioning+Command Name : NetworkJoinRouterResponse+Type Name : uint32_t+Argument Name : transaction,Type Name : EmberAfZllStatus+Argument Name : status
Cluster Name : ZLLCommissioning+Command Name : NetworkStartResponse+Type Name : uint32_t+Argument Name : transaction,Type Name : EmberAfZllStatus+Argument Name : status,Type Name : uint8_t *+Argument Name : extendedPanId,Type Name : uint8_t+Argument Name : networkUpdateId,Type Name : uint8_t+Argument Name : logicalChannel,Type Name : uint16_t+Argument Name : panId
Cluster Name : ZLLCommissioning+Command Name : ScanResponse+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t+Argument Name : rssiCorrection,Type Name : uint8_t+Argument Name : zigbeeInformation,Type Name : uint8_t+Argument Name : zllInformation,Type Name : uint16_t+Argument Name : keyBitmask,Type Name : uint32_t+Argument Name : responseId,Type Name : uint8_t *+Argument Name : extendedPanId,Type Name : uint8_t+Argument Name : networkUpdateId,Type Name : uint8_t+Argument Name : logicalChannel,Type Name : uint16_t+Argument Name : panId,Type Name : uint16_t+Argument Name : networkAddress,Type Name : uint8_t+Argument Name : numberOfSubDevices,Type Name : uint8_t+Argument Name : totalGroupIds,Type Name : uint8_t+Argument Name : endpointId,Type Name : uint16_t+Argument Name : profileId,Type Name : uint16_t+Argument Name : deviceId,Type Name : uint8_t+Argument Name : version,Type Name : uint8_t+Argument Name : groupIdCount

