Cluster Name : Groups+Command Name : AddGroup+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t *+Argument Name : groupName
Cluster Name : Groups+Command Name : AddGroupIfIdentifying+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t *+Argument Name : groupName
Cluster Name : Groups+Command Name : GetGroupMembership+Type Name : uint8_t+Argument Name : groupCount,Type Name : uint16_t+Argument Name : groupList
Cluster Name : Groups+Command Name : RemoveAllGroups
Cluster Name : Groups+Command Name : RemoveGroup+Type Name : uint16_t+Argument Name : groupId
Cluster Name : Groups+Command Name : ViewGroup+Type Name : uint16_t+Argument Name : groupId
Cluster Name : Identify+Command Name : Identify+Type Name : uint16_t+Argument Name : identifyTime
Cluster Name : Identify+Command Name : IdentifyQuery
Cluster Name : Identify+Command Name : TriggerEffect+Type Name : EmberAfIdentifyEffectIdentifier+Argument Name : effectId,Type Name : EmberAfIdentifyEffectVariant+Argument Name : effectVariant
Cluster Name : LevelControl+Command Name : Move+Type Name : EmberAfMoveMode+Argument Name : moveMode,Type Name : uint8_t+Argument Name : rate,Type Name : uint8_t+Argument Name : optionMask,Type Name : uint8_t+Argument Name : optionOverride
Cluster Name : LevelControl+Command Name : MoveToLevel+Type Name : uint8_t+Argument Name : level,Type Name : uint16_t+Argument Name : transitionTime,Type Name : uint8_t+Argument Name : optionMask,Type Name : uint8_t+Argument Name : optionOverride
Cluster Name : LevelControl+Command Name : MoveToLevelWithOnOff+Type Name : uint8_t+Argument Name : level,Type Name : uint16_t+Argument Name : transitionTime
Cluster Name : LevelControl+Command Name : MoveWithOnOff+Type Name : EmberAfMoveMode+Argument Name : moveMode,Type Name : uint8_t+Argument Name : rate
Cluster Name : LevelControl+Command Name : Step+Type Name : EmberAfStepMode+Argument Name : stepMode,Type Name : uint8_t+Argument Name : stepSize,Type Name : uint16_t+Argument Name : transitionTime,Type Name : uint8_t+Argument Name : optionMask,Type Name : uint8_t+Argument Name : optionOverride
Cluster Name : LevelControl+Command Name : StepWithOnOff+Type Name : EmberAfStepMode+Argument Name : stepMode,Type Name : uint8_t+Argument Name : stepSize,Type Name : uint16_t+Argument Name : transitionTime
Cluster Name : LevelControl+Command Name : Stop+Type Name : uint8_t+Argument Name : optionMask,Type Name : uint8_t+Argument Name : optionOverride
Cluster Name : LevelControl+Command Name : StopWithOnOff
Cluster Name : OnOff+Command Name : Off
Cluster Name : OnOff+Command Name : OffWithEffect+Type Name : EmberAfOnOffEffectIdentifier+Argument Name : effectId,Type Name : uint8_t+Argument Name : effectVariant
Cluster Name : OnOff+Command Name : On
Cluster Name : OnOff+Command Name : OnWithRecallGlobalScene
Cluster Name : OnOff+Command Name : OnWithTimedOff+Type Name : uint8_t+Argument Name : onOffControl,Type Name : uint16_t+Argument Name : onTime,Type Name : uint16_t+Argument Name : offWaitTime
Cluster Name : OnOff+Command Name : Toggle
Cluster Name : Scenes+Command Name : AddScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId,Type Name : uint16_t+Argument Name : transitionTime,Type Name : uint8_t *+Argument Name : sceneName,Type Name : EmberAfSceneExtensionFieldSet+Argument Name : extensionFieldSets
Cluster Name : Scenes+Command Name : CopyScene+Type Name : uint8_t+Argument Name : mode,Type Name : uint16_t+Argument Name : groupIdFrom,Type Name : uint8_t+Argument Name : sceneIdFrom,Type Name : uint16_t+Argument Name : groupIdTo,Type Name : uint8_t+Argument Name : sceneIdTo
Cluster Name : Scenes+Command Name : EnhancedAddScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId,Type Name : uint16_t+Argument Name : transitionTime,Type Name : uint8_t *+Argument Name : sceneName,Type Name : EmberAfSceneExtensionFieldSet+Argument Name : extensionFieldSets
Cluster Name : Scenes+Command Name : EnhancedViewScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : Scenes+Command Name : GetSceneMembership+Type Name : uint16_t+Argument Name : groupId
Cluster Name : Scenes+Command Name : RecallScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId,Type Name : uint16_t+Argument Name : transitionTime
Cluster Name : Scenes+Command Name : RemoveAllScenes+Type Name : uint16_t+Argument Name : groupId
Cluster Name : Scenes+Command Name : RemoveScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : Scenes+Command Name : StoreScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : Scenes+Command Name : ViewScene+Type Name : uint16_t+Argument Name : groupId,Type Name : uint8_t+Argument Name : sceneId
Cluster Name : ZllCommissioning+Command Name : DeviceInformationRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t+Argument Name : startIndex
Cluster Name : ZllCommissioning+Command Name : GetEndpointListRequest+Type Name : uint8_t+Argument Name : startIndex
Cluster Name : ZllCommissioning+Command Name : GetGroupIdentifiersRequest+Type Name : uint8_t+Argument Name : startIndex
Cluster Name : ZllCommissioning+Command Name : IdentifyRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint16_t+Argument Name : identifyDuration
Cluster Name : ZllCommissioning+Command Name : NetworkJoinEndDeviceRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t *+Argument Name : extendedPanId,Type Name : EmberAfKeyIndex+Argument Name : keyIndex,Type Name : /* TYPE WARNING: security_key defaults to */ uint8_t * +Argument Name : encryptedNetworkKey,Type Name : uint8_t+Argument Name : networkUpdateId,Type Name : uint8_t+Argument Name : logicalChannel,Type Name : uint16_t+Argument Name : panId,Type Name : uint16_t+Argument Name : networkAddress,Type Name : uint16_t+Argument Name : groupIdentifiersBegin,Type Name : uint16_t+Argument Name : groupIdentifiersEnd,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeBegin,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeEnd,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeBegin,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeEnd
Cluster Name : ZllCommissioning+Command Name : NetworkJoinRouterRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t *+Argument Name : extendedPanId,Type Name : EmberAfKeyIndex+Argument Name : keyIndex,Type Name : /* TYPE WARNING: security_key defaults to */ uint8_t * +Argument Name : encryptedNetworkKey,Type Name : uint8_t+Argument Name : networkUpdateId,Type Name : uint8_t+Argument Name : logicalChannel,Type Name : uint16_t+Argument Name : panId,Type Name : uint16_t+Argument Name : networkAddress,Type Name : uint16_t+Argument Name : groupIdentifiersBegin,Type Name : uint16_t+Argument Name : groupIdentifiersEnd,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeBegin,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeEnd,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeBegin,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeEnd
Cluster Name : ZllCommissioning+Command Name : NetworkStartRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t *+Argument Name : extendedPanId,Type Name : EmberAfKeyIndex+Argument Name : keyIndex,Type Name : /* TYPE WARNING: security_key defaults to */ uint8_t * +Argument Name : encryptedNetworkKey,Type Name : uint8_t+Argument Name : logicalChannel,Type Name : uint16_t+Argument Name : panId,Type Name : uint16_t+Argument Name : networkAddress,Type Name : uint16_t+Argument Name : groupIdentifiersBegin,Type Name : uint16_t+Argument Name : groupIdentifiersEnd,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeBegin,Type Name : uint16_t+Argument Name : freeNetworkAddressRangeEnd,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeBegin,Type Name : uint16_t+Argument Name : freeGroupIdentifierRangeEnd,Type Name : uint8_t *+Argument Name : initiatorIeeeAddress,Type Name : uint16_t+Argument Name : initiatorNetworkAddress
Cluster Name : ZllCommissioning+Command Name : NetworkUpdateRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t *+Argument Name : extendedPanId,Type Name : uint8_t+Argument Name : networkUpdateId,Type Name : uint8_t+Argument Name : logicalChannel,Type Name : uint16_t+Argument Name : panId,Type Name : uint16_t+Argument Name : networkAddress
Cluster Name : ZllCommissioning+Command Name : ResetToFactoryNewRequest+Type Name : uint32_t+Argument Name : transaction
Cluster Name : ZllCommissioning+Command Name : ScanRequest+Type Name : uint32_t+Argument Name : transaction,Type Name : uint8_t+Argument Name : zigbeeInformation,Type Name : uint8_t+Argument Name : zllInformation

