#!/bin/bash

shopt -s extglob

LOC=`dirname "$0"`
SUM=0

for A in ${LOC}/../*.xml; do
    xmllint --noout --schema ${LOC}/../schema/zcl.xsd  $A
    SUM=$(( $SUM + $?))
done

for A in ${LOC}/../../silabs/*.xml; do
    xmllint --noout --schema ${LOC}/../schema/zcl.xsd  $A
    SUM=$(( $SUM + $?))
done

for A in ${LOC}/../../matter/data-model/*.xml; do
    xmllint --noout --schema ${LOC}/../schema/zcl.xsd  $A
    SUM=$(( $SUM + $?))
done

for A in ${LOC}/../../../test/resource/meta/*.xml; do
    xmllint --noout --schema ${LOC}/../schema/zcl.xsd  $A
    SUM=$(( $SUM + $?))
done

for A in ${LOC}/../../../test/resource/custom-cluster/!([b]*|matter*).xml; do
    xmllint --noout --schema ${LOC}/../schema/zcl.xsd  $A
    SUM=$(( $SUM + $?))
done

exit $SUM
