/**
 *
 *    Copyright (c) 2020 Silicon Labs
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// This file is generated by "zap-renderer-api-regen.js".
// Please don't edit manually.

exports.renderer_api_info = [
  { id: 'open', description: 'Open file...' },
  { id: 'save', description: 'Save file...' },
  { id: 'reportFiles', description: 'Reports files selected by the renderer.' },
  { id: 'progressStart', description: 'Start progress indicator.' },
  { id: 'progressEnd', description: 'End progress indicator.' },
  { id: 'debugNavBar', description: 'Show debug navigation bar...' },
  { id: 'setTheme', description: 'Set theme...' },
  { id: 'setItem', description: 'Set item...' },
  { id: 'getItem', description: 'Get item...' },
  { id: 'removeItem', description: 'Remove item...' },
  { id: 'getFileLocation' },
  { id: 'saveFileLocation' },
  { id: 'getStorageItem' },
  { id: 'setStorageItem' },
  { id: 'removeStorageItem' },
  { id: 'debugNavBarOff' },
  { id: 'debugNavBarOn' },
]

exports.id = {
  debugNavBar: 'debugNavBar',
  debugNavBarOff: 'debugNavBarOff',
  debugNavBarOn: 'debugNavBarOn',
  getFileLocation: 'getFileLocation',
  getItem: 'getItem',
  getStorageItem: 'getStorageItem',
  open: 'open',
  progressEnd: 'progressEnd',
  progressStart: 'progressStart',
  removeItem: 'removeItem',
  removeStorageItem: 'removeStorageItem',
  reportFiles: 'reportFiles',
  save: 'save',
  saveFileLocation: 'saveFileLocation',
  setItem: 'setItem',
  setStorageItem: 'setStorageItem',
  setTheme: 'setTheme',
}

exports.notifyKey = { dirtyFlag: 'dirtyFlag', fileBrowse: 'fileBrowse' }

exports.jsonPrefix = 'rendererApiJson:'

exports.observable = {
  debugNavBar: 'debugNavBar',
  progress_attribute: 'progress-message',
  reported_files: 'reported-files',
  themeData: 'data-theme',
}

exports.storageKey = {
  fileSave: 'lastFileLocation_openFileSave',
  theme: 'ui_theme',
}
