#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀   > Pretty quick reformat..."
npx pretty-quick --staged

echo "🚀   > JSdoc regen..."
npx jsdoc src-electron src-shared -r -d ./generated-html/

echo "🚀   > Eslint..."
npx eslint --ext .js,.vue src src-electron src-shared src-script test

echo "🚀   > Update version..."
src-script/zap-update-package-version.js
