#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀   > Pretty quick reformat..."
npx pretty-quick --staged

echo "🚀   > JSdoc regen..."
node src-script/generate-all-api-docs.js
node src-script/generate-template-helper-docs.js
git add docs/api.md
git add docs/helpers.md

echo "🚀   > Eslint..."
npx eslint .

echo "🚀   > Reset version in package.json to 0.0.0..."
src-script/zap-update-package-version.js -fake

echo "🚀   > Check versions in package-lock.json..."
src-script/zap-validate-metafiles.js
